alias reload!='. ~/.zshrc'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias notify="notify-send \"DONE\!\" \"Your thing is done, Ben.\""
alias work="cd ~/projects/frontrow/megarepo && git refresh && ./build.sh build --dev"
alias open='xdg-open'
alias c1="awk '{print \$1}'"
alias c2="awk '{print \$2}'"
alias c3="awk '{print \$3}'"
alias c4="awk '{print \$4}'"
alias c5="awk '{print \$5}'"
alias c6="awk '{print \$6}'"
alias c7="awk '{print \$7}'"
alias c8="awk '{print \$8}'"
alias c9="awk '{print \$9}'"
